- name: app setup
  ansible.builtin.import_role:
    name: commom
    tasks_from: app-setup

- name: python
  ansible.builtin.import_role:
    name: commom
    tasks_from: python

- name: system restart
  ansible.builtin.import_role:
    name: commom
    tasks_from: systemd
