- name: app setup
  ansible.builtin.import_role:
    name: commom
    tasks_from: app-setup

- name: node js
  ansible.builtin.import_role:
    name: commom
    tasks_from: nodejs

- name: system restart
  ansible.builtin.import_role:
    name: commom
    tasks_from: systemd

